image:
  file: .gitpod.Dockerfile
ports:
  - port: 9000
  - port: 9001
  - port: 8081
tasks:
  - init: |
        export GO111MODULE=on
        go get google.golang.org/protobuf/cmd/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
        export PATH="$PATH:$(go env GOPATH)/bin"
